import {getToken} from "../../utils/auth";
const app = {
    state:{
        collapsed:false,
        currentMenu:JSON.parse(getToken('currentMenu')) || 0,
        menu:[
            {
                title:'系统配置',
                icon:'user',
                key:'1',
                path:'/system',
                children:[
                    {
                        title:'首页数据配置',
                        key:'1.1',
                        icon:'xitongjichuguanli',
                        path:'/homeConfig',
                        children:[]
                    },
                    {
                        title:'菜单设置',
                        key:'1.2',
                        icon:'dibucaidan-',
                        path:'/menuConfig',
                        children:[]
                    },
                    {
                        title:'角色设置',
                        key:'1.3',
                        icon:'quanxianguanli',
                        path:'/roleConfig',
                        children:[]
                    }
                ],
            },
            {
                title:'功能管理',
                key:'2',
                icon:'laptop',
                path:'/service',
                children:[
                    {
                        title:'文章管理',
                        key:'2.1',
                        icon:'mingxi',
                        path:'/article',
                        children:[
                            {
                                title:'三级菜单2',
                                key:'2.1.1',
                                icon:'user',
                                path:'/',
                                children:[]
                            },
                            {
                                title:'三级菜单2',
                                key:'2.1.2',
                                icon:'user',
                                path:'/',
                                children:[]
                            },
                            {
                                title:'三级菜单2',
                                key:'2.1.3',
                                icon:'user',
                                path:'/',
                                children:[]
                            }
                        ]
                    },
                    {
                        title:'用户管理',
                        key:'2.2',
                        icon:'duoyonghu',
                        path:'/user',
                        children:[]
                    },
                    {
                        title:'活动管理',
                        key:'2.3',
                        icon:'duobaozhuanqu-',
                        path:'/event',
                        children:[]
                    },
                    {
                        title:'商户管理',
                        key:'2.4',
                        icon:'user',
                        path:'/store',
                        children:[
                            {
                                title:'三级菜单2',
                                key:'2.4.1',
                                icon:'user',
                                path:'/',
                                children:[]
                            },
                            {
                                title:'三级菜单2',
                                key:'2.4.2',
                                icon:'user',
                                path:'/',
                                children:[]
                            },
                            {
                                title:'三级菜单2',
                                key:'2.4.3',
                                icon:'user',
                                path:'/',
                                children:[]
                            }
                        ]
                    },
                ]
            },
            {
                title:'资源管理',
                key:'3',
                icon:'notification',
                path:'/assets',
                children:[
                    {
                        title:'图片管理',
                        key:'3.1',
                        icon:'tupian',
                        path:'/image',
                        children:[]
                    },
                    {
                        title:'素材管理',
                        key:'3.2',
                        icon:'shenjing',
                        path:'/material',
                        children:[]
                    },
                    {
                        title:'音乐管理',
                        key:'3.3',
                        icon:'yinle',
                        path:'/music',
                        children:[]
                    }
                ]
            },
            {
                title:'项目管理',
                key:'4',
                icon:'notification',
                path:'/resource',
                children:[
                    {
                        title:'图片管理',
                        key:'4.1',
                        icon:'user',
                        path:'/image',
                        children:[]
                    },
                    {
                        title:'素材管理',
                        key:'4.2',
                        icon:'user',
                        path:'/material',
                        children:[]
                    },
                    {
                        title:'音乐管理',
                        key:'4.3',
                        icon:'user',
                        path:'/music',
                        children:[]
                    }
                ]
            },
            {
                title:'其他',
                icon:'notification',
                key:'5',
                path:'/',
                children:[
                    {
                        title:'二级菜单4',
                        key:'5.1',
                        icon:'user',
                        path:'/',
                        children:[
                            {
                                title:'三级菜单4',
                                key:'5.1.1',
                                icon:'user',
                                path:'/',
                            },
                            {
                                title:'三级菜单4',
                                key:'5.1.2',
                                icon:'user',
                                path:'/',
                            },
                            {
                                title:'三级菜单4',
                                key:'5.1.3',
                                icon:'user',
                                path:'/',
                            },
                            {
                                title:'三级菜单4',
                                key:'5.1.4',
                                icon:'user',
                                path:'/',
                            },
                            {
                                title:'三级菜单4',
                                key:'5.1.5',
                                icon:'user',
                                path:'/',
                            },
                            {
                                title:'三级菜单4',
                                key:'5.1.6',
                                icon:'user',
                                path:'/',
                            }
                        ]
                    },
                    {
                        title:'二级菜单4',
                        key:'5.2',
                        icon:'user',
                        path:'/',
                        children:[
                            {
                                title:'三级菜单4',
                                key:'5.2.1',
                                icon:'user',
                                path:'/',
                                children:[]
                            },
                            {
                                title:'三级菜单4',
                                key:'5.2.2',
                                icon:'user',
                                path:'/',
                                children:[]
                            }
                        ]
                    },
                    {
                        title:'二级菜单4',
                        key:'5.3',
                        icon:'user',
                        path:'/',
                        children:[
                            {
                                title:'三级菜单4',
                                key:'5.3.1',
                                icon:'user',
                                path:'/',
                                children:[]
                            }
                        ]
                    },
                    {
                        title:'二级菜单4',
                        key:'5.4',
                        icon:'user',
                        path:'/',
                        children:[]
                    },
                    {
                        title:'二级菜单4',
                        key:'5.5',
                        icon:'user',
                        path:'/',
                        children:[
                            {
                                title:'三级菜单4',
                                key:'5.5.1',
                                icon:'user',
                                path:'/',
                                children:[]
                            },
                            {
                                title:'三级菜单4',
                                key:'5.5.2',
                                icon:'user',
                                path:'/',
                                children:[]
                            },
                            {
                                title:'三级菜单4',
                                key:'5.5.3',
                                icon:'user',
                                path:'/',
                                children:[]
                            }
                        ]
                    }
                ]
            }
        ],
        menuSelect:[],
        defaultMenuKey:JSON.parse(getToken('menuDfKey')) || [],
        openKey:JSON.parse(getToken('openKeys')) || [],
        breadcrumb:JSON.parse(getToken('breadCrumb')) || []
    },
    mutations:{
        CHANGE_COLLAPSED(state,collapsed){
            state.collapsed = collapsed
        },
        CHANGE_CURRENT_MENU(state,current){
            state.currentMenu = current;
            for(let i=0;i<state.menu.length;i++){
                if(i == state.currentMenu){
                    state.menuSelect = state.menu[i].children
                }
            }
        },
        SAVE_MENU(state,menu){
            state.menu = menu
        },
        SAVE_MENU_SELECT(state,menuSelect){
            state.menuSelect = menuSelect
        },
        SAVE_BREAD_CRUMB(state,arr){
            state.breadcrumb = arr;
        },
        SAVE_MENU_KEY(state,key){
            state.defaultMenuKey = key;
        },
        SAVE_OPEN_KEY(state,key){
            state.openKey = key;
        }
    },
    actions:{
        CHANGE_COLLAPSED({commit},state){
            commit('CHANGE_COLLAPSED',state);
        },
        CHANGE_CURRENT_MENU({commit},state){
            commit('CHANGE_CURRENT_MENU',state)
        },
        SAVE_MENU({commit},state){
            commit('CHANGE_MENU',state)
        },
        SAVE_MENU_SELECT({commit},state){
            commit('SAVE_MENU_SELECT',state)
        },
        SAVE_BREAD_CRUMB({commit},state){
            commit('SAVE_BREAD_CRUMB',state)
        },
        SAVE_MENU_KEY({commit},state){
            commit('SAVE_MENU_KEY',state)
        },
        SAVE_OPEN_KEY({commit},state){
            commit('SAVE_OPEN_KEY',state)
        }
    }
}
export default app




